from __future__ import annotations

import io
import base64
import hashlib
import hmac
from datetime import datetime, timedelta, timezone
from xml.etree import ElementTree

import pytest

google_auth = pytest.importorskip("google.auth.credentials")
gcs_storage = pytest.importorskip("google.cloud.storage")


class HmacSigningCredentials(google_auth.Signing):
    """The official signed-URL API's Signing interface, backed by a synthetic HMAC key.

    Python storage's V2 URL generator supports this signing interface; its V4
    generator hardcodes RSA, so this qualifies native V2 HMAC only.
    """

    def __init__(self, access_id, secret):
        self._access_id = access_id
        self._secret = base64.b64decode(secret)

    @property
    def signer_email(self):
        return self._access_id

    @property
    def signer(self):
        return self

    def sign_bytes(self, message):
        return hmac.new(self._secret, message, hashlib.sha1).digest()


def _native_request(
    client,
    resource,
    method,
    credentials,
    endpoint,
    *,
    data=None,
    headers=None,
    expiration=None,
):
    headers = {**(headers or {}), "content-length": str(len(data or b""))}
    url = resource.generate_signed_url(
        version="v2",
        method=method,
        credentials=credentials,
        api_access_endpoint=endpoint,
        expiration=expiration or datetime.now(timezone.utc) + timedelta(minutes=5),
        headers={
            name: value
            for name, value in (headers or {}).items()
            if name.startswith("x-goog-")
        },
        **(
            {"content_type": headers.get("content-type")}
            if isinstance(resource, gcs_storage.Blob)
            and headers
            and "content-type" in headers
            else {}
        ),
    )
    # The official client's HTTP transport consumes the URL generated by its public signing API.
    return client._http.request(method, url, data=data, headers=headers, timeout=10)


def test_gcs_native_hmac_signed_url_contract(sqrzl_server):
    sqrzl_server.require_provider("gcs")
    if not sqrzl_server.enforce_auth:
        pytest.skip("native HMAC requires the authenticated storage lane")
    client = gcs_storage.Client(
        project="sqrzl",
        credentials=google_auth.AnonymousCredentials(),
        client_options={"api_endpoint": sqrzl_server.api_url},
    )
    credentials = HmacSigningCredentials(
        sqrzl_server.gcs_hmac_access_id, sqrzl_server.gcs_hmac_secret
    )
    bucket = client.bucket(sqrzl_server.bucket_name("sdk-gcs-native"))
    blob = bucket.blob("folder/native.txt")
    request = lambda resource, method, **kwargs: _native_request(
        client, resource, method, credentials, sqrzl_server.api_url, **kwargs
    )
    assert request(bucket, "PUT", data=b"").status_code == 200
    headers = {"content-type": "text/plain", "x-goog-meta-owner": "native-sdk"}
    assert (
        request(blob, "PUT", data=b"native hmac payload", headers=headers).status_code
        == 200
    )
    fetched = request(blob, "GET")
    assert fetched.status_code == 200
    assert fetched.content == b"native hmac payload"
    assert fetched.headers["x-goog-meta-owner"] == "native-sdk"
    assert request(blob, "GET", headers={"range": "bytes=7-10"}).content == b"hmac"

    for bad_credentials, expiration, code in [
        (
            HmacSigningCredentials(
                sqrzl_server.gcs_hmac_access_id, base64.b64encode(b"wrong-key").decode()
            ),
            None,
            "SignatureDoesNotMatch",
        ),
        (
            HmacSigningCredentials("wrong-access", sqrzl_server.gcs_hmac_secret),
            None,
            "AccessDenied",
        ),
        (
            credentials,
            datetime.now(timezone.utc) - timedelta(minutes=1),
            "AccessDenied",
        ),
    ]:
        denied = _native_request(
            client,
            blob,
            "PUT",
            bad_credentials,
            sqrzl_server.api_url,
            data=b"replacement",
            expiration=expiration,
        )
        assert denied.status_code == 403
        assert ElementTree.fromstring(denied.content).findtext("Code") == code
        assert request(blob, "GET").content == b"native hmac payload"
    assert request(blob, "DELETE").status_code == 204
    assert request(bucket, "DELETE").status_code == 204


def _client(sqrzl_server):
    credentials = google_auth.AnonymousCredentials()
    if sqrzl_server.enforce_auth:
        google_oauth2 = pytest.importorskip("google.oauth2.credentials")
        credentials = google_oauth2.Credentials(token=sqrzl_server.gcs_hmac_secret)
    return gcs_storage.Client(
        project="sqrzl",
        credentials=credentials,
        client_options={"api_endpoint": sqrzl_server.api_url},
    )


def test_gcs_core_json_workflows(sqrzl_server):
    sqrzl_server.require_provider("gcs")
    client = _client(sqrzl_server)
    bucket_name = sqrzl_server.bucket_name("sdk-gcs-core")
    blob_name = "folder/hello.txt"

    bucket = client.bucket(bucket_name)
    bucket.create()
    blob = bucket.blob(blob_name)
    blob.metadata = {"owner": "support"}
    blob.upload_from_string("hello gcs sdk", content_type="text/plain")

    blob.reload()
    assert blob.metadata["owner"] == "support"
    assert blob.size == len(b"hello gcs sdk")

    assert blob.download_as_bytes(start=6, end=8) == b"gcs"
    assert [item.name for item in client.list_blobs(bucket, prefix="folder/")] == [
        blob_name
    ]

    blob.delete()
    bucket.delete()


def test_gcs_resumable_upload_workflow(sqrzl_server):
    sqrzl_server.require_provider("gcs")
    client = _client(sqrzl_server)
    bucket_name = sqrzl_server.bucket_name("sdk-gcs-resumable")
    blob_name = "large/resumable.txt"

    bucket = client.bucket(bucket_name)
    bucket.create()
    blob = bucket.blob(blob_name)
    payload = b"g" * (9 * 1024 * 1024 + 17)
    blob.chunk_size = 256 * 1024
    blob.upload_from_file(
        io.BytesIO(payload),
        rewind=True,
        size=len(payload),
        content_type="text/plain",
    )

    assert blob.download_as_bytes() == payload
    blob.delete()
    bucket.delete()
