services:
  sqrzl:
    container_name: sqrzl
    hostname: sqrzl
    build: .
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      SQRZL_BLOBS_PATH: /app/blobs
      SQRZL_LOG_FORMAT: text
      SQRZL_ACCESS_KEY_ID: admin
      SQRZL_SECRET_ACCESS_KEY: sqrzl-secret
    volumes:
      - sqrzl-blobs:/app/blobs

volumes:
  sqrzl-blobs:
